### ISSUE TITLE
Is ApiClient threadsafe?

### ISSUE THREAD

**Issue by nedtwigg** [ActiveCampaign/postmark-java#57]
I can't find any documentation specifying whether we can use a single ApiClient instance, or if we need a separate ApiClient for each thread.

**Comment by nedtwigg** [comment]
Thanks! Thread unsafe works just fine, easy to solve with ThreadLocal. Just wanted a doc on what the intent was.

**Comment by ibalosh** [comment]
Hey @nedtwigg 

actually, my assumption seem to have been wrong. The http client used by the library is thread safe. However I did a small release today, version 1.10.21 with small fine tuning to it.

Feel free to use the latest version, and you should be good to go.
