### ISSUE TITLE
Support for Jakarta EE

### ISSUE THREAD

**Issue by rafafialho6** [ActiveCampaign/postmark-java#58]
Summary: We use Quarkus framework (Right now at `2.16.7.Final`) and the existing `1.9.0` Postmark version.
Quarkus has recently launched Quarkus `3.0` and `3.1` that completely move to Jakarta EE 10 (that doesn't keep compatibility with Java EE/Jakarta 8.

**Existing issue**
![image](https://github.com/ActiveCampaign/postmark-java/assets/20357228/4aa3789a-316b-4647-8bf7-eceac3945a86)
These would move to `jakarta.*...`

**Describe the solution you'd like**
A version that supports Jakarta EE.

**Additional context**
https://medium.com/@AlexanderObregon/how-to-migrate-from-java-ee-to-jakarta-ee-tips-and-best-practices-f19530c3bb1d

**Comment by ibalosh** [comment]
Hi @rafafialho6 

did you try the latest version, which is 1.10.21? We have migrated to new http client, which supports Jakarta, and removes javax dependencies.

Make sure to have migrated to new groupid , which you can check out in readme [here](https://github.com/ActiveCampaign/postmark-java).

**Comment by rafafialho6** [comment]
@ibalosh thanks, Igor!
Will check that out and I think this should be resolved then. (We are still using `1.9.0`)

**Comment by rafafialho6** [comment]
@ibalosh thanks, Igor!
Will check that out and I think this should be resolved then. (We are still using 1.9.0)
