### ISSUE TITLE
Spring boot version 3.XX support

### ISSUE THREAD

**Issue by waldirmarques** [ActiveCampaign/postmark-java#62]
Currently the lib does not support use with spring boot higher than version 3, due to the javax. Do you have any plans to update the lib?

**Comment by mlilback** [comment]
Yes, Jakarta EE 9+ (current is 10) switched from the javax namespace to the jakarta namespace. Upgrading to the latest Dropwizard/Jetty just caused this problem for me. I was using version 1.9 of postmarkapp in my pom.xml. I changed it to 1.11 and the problem was fixed.

**Comment by ibalosh** [comment]
yes, we updated underlying HTTP client so we no longer use javax, only need to make sure to use latest version of the library. CHange was made in [version 1.10.0](https://github.com/ActiveCampaign/postmark-java/releases/tag/1.10.0)

**Comment by ivansenic** [comment]
@ibalosh This version is not yet available on maven, did you change the group or the artifact ids as well? https://mvnrepository.com/artifact/com.wildbit.java/postmark

UPDATE: Yes I see now group has been change to `com.postmarkapp`, just in case anyone wanders.
