### ISSUE TITLE
Metadata field is not present in "Bounce" class

### ISSUE THREAD

**Issue by robertop87** [ActiveCampaign/postmark-java#63]
**Describe the bug**
Metadata field in Bounce response object is not present.
It is very important for custom integrations, because it provides specific custom information for API consumers.

**To Reproduce**
Provide steps to reproduce the behavior:
1. Open the Bounce.java
2. Verify that "metadata" field is not present

**Expected behavior**
"metadata" field must be present, and it should be Map<String, String> or Map<String, Object>

**Java (please complete the following information):**
 No related to java

**Additional context**
 None

**Comment by ewood-ac** [comment]
@robertop87 - If you [review our documentation](https://postmarkapp.com/developer/api/bounce-api) there is not a mention of metadata being present on a bounce. Can you explain what you are looking for?

**Comment by robertop87** [comment]
Hello @ewood-ac thank for take this issue.

I just reviewed the doc for second time, and you are right, "Metadata" is not mentioned there.

But recently I'm working with a client who is asking me to read and store this "Metadata" which should be present in the response because my client required it directly to Postmark and looks it was accepted.

An example of this value in the JSON response is the next:

```json
"Metadata": {
  "customName1" : <some-value>,
  "customName2" : <some-value>
}

```

And the "Metadata" could have many customName.

**Comment by ewood-ac** [comment]
@robertop87 - Currently the only place that the metadata you are referencing is used is the [bounce webhook](https://postmarkapp.com/developer/webhooks/bounce-webhook). This is not an issue with the SDK rather it is a product feature.
If you need to request an update. Please contact our Customer Service to request a change to our Bounce payload.

**Comment by ewood-ac** [comment]
@robertop87 - Please contact our Customer Service if you would like to request a change to our Bounce payload.
